name: imath
description: A mathematics learning app.
publish_to: 'none'
#publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_infinite_scroll: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  camera: ^0.11.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.2.0
  logger: ^2.6.1
  image: ^4.1.7
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.1
  #provider: ^6.1.1
  shared_preferences: ^2.5.3
  flutter_simple_treeview: ^3.0.2
  markdown_widget: ^2.3.2+8
  gpt_markdown: ^1.0.18
  #gpt_markdown:
  #  path: /opt/flutter/packages/gpt_markdown
  dio: ^5.8.0+1
  flutter_tex: ^5.0.6
  flutter_smart_dialog: ^4.9.8+8
  hive: ^2.2.3
  qr_flutter: ^4.1.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  isar_flutter_libs: ^3.1.0+1
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.4.1
  common_utils: ^2.1.0
  flutter_math_fork: ^0.7.4
  #  path: /opt/flutter/packages/flutter_math_fork
  #sqflite: ^2.4.2
  #sqflite_common_ffi: ^2.3.5
  oauth2: ^2.0.3
  #internet_connection_checker: ^3.0.1
  go_router: ^16.0.0
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^3.2.0
  desktop_drop: ^0.6.0
  dotted_border: ^3.0.1
  flutter_quill: ^11.4.1
  file_picker: ^10.1.9
  flutter_native_splash: ^2.4.6
  image_cropper: ^9.1.0
  pinput: ^5.0.1
  pin_code_fields: ^8.0.1
  google_fonts: ^6.2.1
  universal_platform: ^1.1.0
  fleather: ^1.23.0

  delta_to_html: ^0.2.2
  flutter_html: ^3.0.0
  flutter_quill_delta_from_html: ^1.5.2
  animated_tree_view: ^2.3.0
  carousel_slider: ^5.1.1
  pull_to_refresh: ^2.0.0
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  slider_captcha: ^1.0.2
  easy_refresh: ^3.4.0
  flutter_spinkit: ^5.2.1
  simple_animations: ^5.2.0
  intl: ^0.20.2
  quill_native_bridge: ^11.0.1
  flutter_quill_extensions: ^11.0.0
  flutter_html_math: ^3.0.0
  html_editor_enhanced: ^2.7.1

#    git:
##      url: https://github.com/yabipi/flutter_math.git
#      # 如果需要特定分支
#      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 